// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHfzpzBBOG-Gm_YXUD3eY2z4J7fT_zTIc',
    appId: '1:758905646277:web:061c0f666f3bbcf5c794ac',
    messagingSenderId: '758905646277',
    projectId: 'quickchat-pbm',
    authDomain: 'quickchat-pbm.firebaseapp.com',
    storageBucket: 'quickchat-pbm.firebasestorage.app',
    measurementId: 'G-PENXL39T0X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcXbJGjwehi5rNgevWbCRzI_LSShmPRfU',
    appId: '1:758905646277:android:a5b794bfe0842b78c794ac',
    messagingSenderId: '758905646277',
    projectId: 'quickchat-pbm',
    storageBucket: 'quickchat-pbm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFoWn1Cqt8W8mXG-pxV_xc8F3TMWE_IJM',
    appId: '1:758905646277:ios:42c0dd267c91ca46c794ac',
    messagingSenderId: '758905646277',
    projectId: 'quickchat-pbm',
    storageBucket: 'quickchat-pbm.firebasestorage.app',
    iosBundleId: 'com.example.quickchat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFoWn1Cqt8W8mXG-pxV_xc8F3TMWE_IJM',
    appId: '1:758905646277:ios:42c0dd267c91ca46c794ac',
    messagingSenderId: '758905646277',
    projectId: 'quickchat-pbm',
    storageBucket: 'quickchat-pbm.firebasestorage.app',
    iosBundleId: 'com.example.quickchat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHfzpzBBOG-Gm_YXUD3eY2z4J7fT_zTIc',
    appId: '1:758905646277:web:d54cbb0aea5b24cfc794ac',
    messagingSenderId: '758905646277',
    projectId: 'quickchat-pbm',
    authDomain: 'quickchat-pbm.firebaseapp.com',
    storageBucket: 'quickchat-pbm.firebasestorage.app',
    measurementId: 'G-N79MWZD126',
  );
}
